# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtractionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_evidence_links', to='documents.documentchunk')),
            ],
            options={
                'ordering': ('extraction_result_id', 'document_chunk__chunk_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AIExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='1', max_length=40)),
                ('visibility_scope', models.CharField(blank=True, choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_job', to='ai.airequestlog')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_jobs', to='ai.promptversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extraction_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_extraction_jobs', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AIExtractionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('summary', 'Summary'), ('field', 'Research field'), ('method', 'Research method'), ('tag', 'AI tag'), ('variable', 'Variable'), ('dataset', 'Dataset'), ('relationship', 'Relationship')], max_length=30)),
                ('candidate_data', models.JSONField()),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('schema_version', models.CharField(max_length=40)),
                ('visibility_scope', models.CharField(blank=True, choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('candidate', 'Candidate knowledge'), ('superseded', 'Superseded')], db_index=True, default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_chunks', models.ManyToManyField(related_name='ai_extraction_results', through='review.AIExtractionEvidence', to='documents.documentchunk')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='review.aiextractionjob')),
                ('primary_evidence_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_extraction_results', to='documents.documentchunk')),
            ],
            options={
                'ordering': ('job_id', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='aiextractionevidence',
            name='extraction_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='review.aiextractionresult'),
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('research_work', 'Research work'), ('professor', 'Professor'), ('taxonomy', 'Taxonomy'), ('knowledge_edge', 'Knowledge edge')], max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('field_path', models.CharField(max_length=200)),
                ('current_value', models.JSONField(blank=True, default=dict)),
                ('candidate_value', models.JSONField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('teacher_review', 'Teacher review requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', max_length=24)),
                ('visibility_scope', models.CharField(blank=True, choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_items', to=settings.AUTH_USER_MODEL)),
                ('extraction_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_item', to='review.aiextractionresult')),
            ],
            options={
                'ordering': ('state', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('edit', 'Edit and approve'), ('reject', 'Reject'), ('request_teacher_review', 'Request teacher review'), ('archive', 'Archive')], max_length=30)),
                ('previous_state', models.CharField(choices=[('pending', 'Pending'), ('teacher_review', 'Teacher review requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=24)),
                ('resulting_state', models.CharField(choices=[('pending', 'Pending'), ('teacher_review', 'Teacher review requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=24)),
                ('decided_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='review.reviewitem')),
            ],
            options={
                'ordering': ('review_item_id', 'created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='aiextractionjob',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version', ''), _negated=True), name='review_job_schema_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='aiextractionresult',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version', ''), _negated=True), name='review_result_schema_version_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='aiextractionevidence',
            constraint=models.UniqueConstraint(fields=('extraction_result', 'document_chunk'), name='review_result_evidence_chunk_unique'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.CheckConstraint(condition=models.Q(('field_path', ''), _negated=True), name='review_item_field_path_not_empty'),
        ),
    ]
