# Generated by Django 5.2.16 on 2026-07-18 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_governance_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='confidence',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='extraction_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='model',
            field=models.CharField(blank=True, default='deterministic-heuristic', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='source_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
