# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviewitem_confidence_reviewitem_evidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiextractionevidence',
            options={'ordering': ('extraction_result_id', 'document_chunk__chunk_index', 'id'), 'verbose_name': 'AI 擷取證據', 'verbose_name_plural': 'AI 擷取證據'},
        ),
        migrations.AlterModelOptions(
            name='aiextractionjob',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'AI 擷取工作', 'verbose_name_plural': 'AI 擷取工作'},
        ),
        migrations.AlterModelOptions(
            name='aiextractionresult',
            options={'ordering': ('job_id', 'created_at', 'id'), 'verbose_name': 'AI 擷取結果', 'verbose_name_plural': 'AI 擷取結果'},
        ),
        migrations.AlterModelOptions(
            name='reviewdecision',
            options={'ordering': ('review_item_id', 'created_at', 'id'), 'verbose_name': '審核決策', 'verbose_name_plural': '審核決策'},
        ),
        migrations.AlterModelOptions(
            name='reviewitem',
            options={'ordering': ('state', 'created_at', 'id'), 'verbose_name': '審核項目', 'verbose_name_plural': '審核項目'},
        ),
        migrations.AlterField(
            model_name='aiextractionjob',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('succeeded', '成功'), ('failed', '失敗'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiextractionjob',
            name='visibility_scope',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiextractionresult',
            name='result_type',
            field=models.CharField(choices=[('summary', '摘要'), ('field', '研究領域'), ('method', '研究方法'), ('tag', 'AI 標籤'), ('variable', '變數'), ('dataset', '資料集'), ('relationship', '關係')], max_length=30),
        ),
        migrations.AlterField(
            model_name='aiextractionresult',
            name='status',
            field=models.CharField(choices=[('candidate', '候選知識'), ('superseded', '已取代')], db_index=True, default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiextractionresult',
            name='visibility_scope',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='action',
            field=models.CharField(choices=[('approve', '核准'), ('edit', '編輯並核准'), ('reject', '拒絕'), ('request_teacher_review', '請教師審核'), ('archive', '封存')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='previous_state',
            field=models.CharField(choices=[('pending', '待審核'), ('teacher_review', '教師審核中'), ('approved', '已核准'), ('rejected', '已拒絕'), ('archived', '已封存')], max_length=24),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='resulting_state',
            field=models.CharField(choices=[('pending', '待審核'), ('teacher_review', '教師審核中'), ('approved', '已核准'), ('rejected', '已拒絕'), ('archived', '已封存')], max_length=24),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='state',
            field=models.CharField(choices=[('pending', '待審核'), ('teacher_review', '教師審核中'), ('approved', '已核准'), ('rejected', '已拒絕'), ('archived', '已封存')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='target_type',
            field=models.CharField(choices=[('research_work', '研究成果'), ('professor', '教師'), ('taxonomy', '分類'), ('knowledge_edge', '知識關係')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='visibility_scope',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='', max_length=20),
        ),
    ]
