# Generated by Django 5.2.16 on 2026-07-16 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_system_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=120)),
                ('target_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type', ''), _negated=True), name='accounts_audit_event_type_not_empty')],
            },
        ),
    ]
