# Generated by Django 5.2.16 on 2026-07-16 11:12

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('fju_cloud_email', models.EmailField(max_length=254)),
                ('department_code', models.CharField(db_index=True, max_length=32)),
                ('program', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('master', 'Master'), ('phd', 'PhD'), ('other', 'Other')], max_length=32)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('enrollment_status', models.CharField(choices=[('active', 'Active'), ('leave', 'Leave'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=32)),
                ('project_eligibility', models.BooleanField(default=False)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=160)),
                ('source_version', models.CharField(max_length=80)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_roster_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('student_id', '-effective_start'),
            },
        ),
        migrations.CreateModel(
            name='StudentRegistrationOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('fju_cloud_email', models.EmailField(db_index=True, max_length=254)),
                ('backup_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=40)),
                ('otp_hash', models.CharField(max_length=256)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roster_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_otps', to='accounts.studentroster')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('backup_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roster_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_profiles', to='accounts.studentroster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentroster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('student_id'), django.db.models.functions.text.Lower('fju_cloud_email'), models.F('source_version'), name='accounts_roster_student_email_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='studentroster',
            constraint=models.CheckConstraint(condition=models.Q(('student_id', ''), _negated=True), name='accounts_roster_student_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='studentroster',
            constraint=models.CheckConstraint(condition=models.Q(('department_code', ''), _negated=True), name='accounts_roster_department_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='studentroster',
            constraint=models.CheckConstraint(condition=models.Q(('source_version', ''), _negated=True), name='accounts_roster_source_version_not_empty'),
        ),
    ]
