# Generated by Django 5.2.16 on 2026-07-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentroster_studentregistrationotp_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('hard_delete_user', 'Can hard delete users referenced by governance audit records'),)},
        ),
    ]
