# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': '稽核紀錄', 'verbose_name_plural': '稽核紀錄'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('display_name', 'slug'), 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrationotp',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': '學生註冊 OTP', 'verbose_name_plural': '學生註冊 OTP'},
        ),
        migrations.AlterModelOptions(
            name='studentroster',
            options={'ordering': ('student_id', '-effective_start'), 'verbose_name': '學生名冊', 'verbose_name_plural': '學生名冊'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('hard_delete_user', '可直接刪除受治理紀錄保護的使用者'),), 'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '使用者個人資料', 'verbose_name_plural': '使用者個人資料'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ('user_id', 'role_id'), 'verbose_name': '使用者角色', 'verbose_name_plural': '使用者角色'},
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='enrollment_status',
            field=models.CharField(choices=[('active', '在學'), ('leave', '休學'), ('graduated', '畢業'), ('withdrawn', '退學'), ('suspended', '停學')], db_index=True, default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='program',
            field=models.CharField(choices=[('undergraduate', '大學部'), ('master', '碩士班'), ('phd', '博士班'), ('other', '其他')], max_length=32),
        ),
    ]
