# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('research_work', 'Research work'), ('professor', 'Professor'), ('student', 'Student'), ('research_field', 'Research field'), ('research_method', 'Research method'), ('ai_tag', 'AI tag'), ('dataset', 'Dataset'), ('variable', 'Variable'), ('news_event', 'News event')], db_index=True, max_length=40)),
                ('object_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='admin', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('node_type', 'label', 'id'),
                'constraints': [models.UniqueConstraint(fields=('node_type', 'object_id'), name='knowledge_graph_node_type_object_unique'), models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='knowledge_graph_node_label_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('advised_by', 'Advised by'), ('authored_by', 'Authored by'), ('belongs_to_field', 'Belongs to field'), ('uses_method', 'Uses method'), ('has_tag', 'Has tag'), ('uses_dataset', 'Uses dataset'), ('studies_variable', 'Studies variable'), ('related_to_news_event', 'Related to news event'), ('similar_to_work', 'Similar to work')], db_index=True, max_length=40)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evidence_source_type', models.CharField(choices=[('manual', 'Manual'), ('source_document', 'Source document'), ('document_chunk', 'Document chunk'), ('ai_extraction', 'AI extraction')], default='manual', max_length=30)),
                ('evidence_source_id', models.UUIDField(blank=True, null=True)),
                ('evidence_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_edges_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='knowledge_graph.knowledgenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='knowledge_graph.knowledgenode')),
            ],
            options={
                'ordering': ('source_id', 'edge_type', 'target_id'),
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'edge_type'), name='knowledge_graph_edge_unique'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='knowledge_graph_edge_confidence_range'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='knowledge_graph_edge_not_self')],
            },
        ),
    ]
