# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeedge',
            options={'ordering': ('source_id', 'edge_type', 'target_id'), 'verbose_name': '知識關係', 'verbose_name_plural': '知識關係'},
        ),
        migrations.AlterModelOptions(
            name='knowledgenode',
            options={'ordering': ('node_type', 'label', 'id'), 'verbose_name': '知識節點', 'verbose_name_plural': '知識節點'},
        ),
        migrations.AlterField(
            model_name='knowledgeedge',
            name='edge_type',
            field=models.CharField(choices=[('advised_by', '由教師指導'), ('authored_by', '由學生撰寫'), ('belongs_to_field', '屬於研究領域'), ('uses_method', '使用研究方法'), ('has_tag', '具有標籤'), ('uses_dataset', '使用資料集'), ('studies_variable', '研究變數'), ('related_to_news_event', '關聯新聞事件'), ('similar_to_work', '相似研究成果')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='knowledgeedge',
            name='evidence_source_type',
            field=models.CharField(choices=[('manual', '人工'), ('source_document', '原始文件'), ('document_chunk', '文件段落'), ('ai_extraction', 'AI 擷取')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='knowledgeedge',
            name='status',
            field=models.CharField(choices=[('candidate', '候選'), ('approved', '已核准'), ('rejected', '已拒絕'), ('archived', '已封存')], db_index=True, default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='node_type',
            field=models.CharField(choices=[('research_work', '研究成果'), ('professor', '教師'), ('student', '學生'), ('research_field', '研究領域'), ('research_method', '研究方法'), ('ai_tag', 'AI 標籤'), ('dataset', '資料集'), ('variable', '變數'), ('news_event', '新聞事件')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('archived', '封存')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='admin', max_length=20),
        ),
    ]
