# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('undergraduate_project', 'Undergraduate project'), ('master_thesis', 'Master thesis'), ('research_project', 'Research project'), ('journal_article', 'Journal article'), ('conference_paper', 'Conference paper'), ('other', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, editable=False, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('language', models.CharField(default='zh-Hant', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('ai_extracted', 'AI extracted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=24)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='public', max_length=20)),
                ('source_quality', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_works_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_works_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=160)),
                ('public_display_name', models.CharField(blank=True, max_length=160)),
                ('is_name_public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='research_student_name_not_empty'), models.CheckConstraint(condition=models.Q(('normalized_name', ''), _negated=True), name='research_student_normalized_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='WorkAdvisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary advisor'), ('co_advisor', 'Co-advisor'), ('other', 'Other')], default='primary', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor_links', to='professors.professor')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_links', to='research.researchwork')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='researchwork',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='research_works', through='research.WorkAdvisor', to='professors.professor'),
        ),
        migrations.CreateModel(
            name='WorkAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_links', to='research.researchwork')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_links', to='research.student')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='researchwork',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='research_works', through='research.WorkAuthor', to='research.student'),
        ),
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance', models.CharField(choices=[('core', 'Core'), ('related', 'Related'), ('weak', 'Weak'), ('incidental', 'Incidental')], default='related', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported'), ('ai_approved', 'Approved AI candidate')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('archived', 'Archived')], db_index=True, default='approved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_links', to='taxonomy.researchfield')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_links', to='research.researchwork')),
            ],
            options={
                'ordering': ('-is_primary', 'research_field__display_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='researchwork',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='research_works', through='research.WorkField', to='taxonomy.researchfield'),
        ),
        migrations.CreateModel(
            name='WorkMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting')], default='primary', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported'), ('ai_approved', 'Approved AI candidate')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('archived', 'Archived')], db_index=True, default='approved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_links', to='taxonomy.researchmethod')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_links', to='research.researchwork')),
            ],
            options={
                'ordering': ('usage', 'research_method__display_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='researchwork',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='research_works', through='research.WorkMethod', to='taxonomy.researchmethod'),
        ),
        migrations.CreateModel(
            name='FeaturedWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_works_created', to=settings.AUTH_USER_MODEL)),
                ('research_work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='research.researchwork')),
            ],
            options={
                'ordering': ('display_order', '-created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='research_featured_work_window_valid')],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('award_type', models.CharField(choices=[('best_project', 'Best project'), ('excellence', 'Excellence'), ('other', 'Other')], max_length=24)),
                ('award_year', models.PositiveSmallIntegerField(db_index=True)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('organization', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='professors.professor')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='research.researchwork')),
            ],
            options={
                'ordering': ('-award_year', 'name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('research_work', 'name', 'award_year', 'category'), name='research_award_work_name_year_category_unique'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='research_award_name_not_empty'), models.CheckConstraint(condition=models.Q(('award_year__gte', 1900), ('award_year__lte', 2100)), name='research_award_year_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='workadvisor',
            constraint=models.UniqueConstraint(fields=('research_work', 'professor'), name='research_work_advisor_unique'),
        ),
        migrations.AddConstraint(
            model_name='workadvisor',
            constraint=models.UniqueConstraint(fields=('research_work', 'position'), name='research_work_advisor_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='workadvisor',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='research_work_advisor_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.UniqueConstraint(fields=('research_work', 'student'), name='research_work_author_unique'),
        ),
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.UniqueConstraint(fields=('research_work', 'position'), name='research_work_author_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='research_work_author_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='workfield',
            constraint=models.UniqueConstraint(fields=('research_work', 'research_field'), name='research_work_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='workfield',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='research_work_field_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='workfield',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', False), ('relevance', 'core'), _connector='OR'), name='research_primary_field_is_core'),
        ),
        migrations.AddConstraint(
            model_name='workmethod',
            constraint=models.UniqueConstraint(fields=('research_work', 'research_method'), name='research_work_method_unique'),
        ),
        migrations.AddConstraint(
            model_name='workmethod',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='research_work_method_confidence_valid'),
        ),
        migrations.AddConstraint(
            model_name='researchwork',
            constraint=models.UniqueConstraint(fields=('normalized_title', 'year', 'work_type'), name='research_work_title_year_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='researchwork',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='research_work_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='researchwork',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_title', ''), _negated=True), name='research_work_normalized_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='researchwork',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900), ('year__lte', 2100)), name='research_work_year_valid'),
        ),
    ]
