# Generated by Django 5.2.16 on 2026-07-16 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchWorkTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploaded", "Uploaded"),
                            ("parsed", "Parsed"),
                            ("ai_extracted", "AI extracted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("uploaded", "Uploaded"),
                            ("parsed", "Parsed"),
                            ("ai_extracted", "AI extracted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_work_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="research.researchwork",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_status", models.F("to_status")), _negated=True
                        ),
                        name="research_work_transition_changes_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="research_work_transition_reason_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("request_id", ""), _negated=True),
                        name="research_work_transition_request_id_not_empty",
                    ),
                ],
            },
        ),
    ]
