# Generated by Django 5.2.16 on 2026-07-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchworktransition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchwork',
            options={'ordering': ('-year', 'title', 'id'), 'permissions': (('hard_delete_researchwork', 'Can hard delete research works and protected governance records'),)},
        ),
    ]
