# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_researchwork_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('-award_year', 'name', 'id'), 'verbose_name': '獎項', 'verbose_name_plural': '獎項'},
        ),
        migrations.AlterModelOptions(
            name='featuredwork',
            options={'ordering': ('display_order', '-created_at'), 'verbose_name': '首頁精選研究', 'verbose_name_plural': '首頁精選研究'},
        ),
        migrations.AlterModelOptions(
            name='researchwork',
            options={'ordering': ('-year', 'title', 'id'), 'permissions': (('hard_delete_researchwork', '可直接刪除研究成果與受保護治理紀錄'),), 'verbose_name': '研究成果', 'verbose_name_plural': '研究成果'},
        ),
        migrations.AlterModelOptions(
            name='researchworktransition',
            options={'ordering': ('created_at', 'id'), 'verbose_name': '研究成果狀態轉換', 'verbose_name_plural': '研究成果狀態轉換'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('display_name', 'id'), 'verbose_name': '研究學生', 'verbose_name_plural': '研究學生'},
        ),
        migrations.AlterModelOptions(
            name='workadvisor',
            options={'ordering': ('position', 'id'), 'verbose_name': '研究成果指導教師', 'verbose_name_plural': '研究成果指導教師'},
        ),
        migrations.AlterModelOptions(
            name='workauthor',
            options={'ordering': ('position', 'id'), 'verbose_name': '研究成果作者', 'verbose_name_plural': '研究成果作者'},
        ),
        migrations.AlterModelOptions(
            name='workfield',
            options={'ordering': ('-is_primary', 'research_field__display_name', 'id'), 'verbose_name': '研究成果領域', 'verbose_name_plural': '研究成果領域'},
        ),
        migrations.AlterModelOptions(
            name='workmethod',
            options={'ordering': ('usage', 'research_method__display_name', 'id'), 'verbose_name': '研究成果方法', 'verbose_name_plural': '研究成果方法'},
        ),
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(choices=[('best_project', '最佳專題'), ('excellence', '優良作品'), ('other', '其他')], max_length=24),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('archived', '封存')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='award',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='source_quality',
            field=models.CharField(choices=[('unknown', '未知'), ('low', '低'), ('medium', '中'), ('high', '高')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('uploaded', '已上傳'), ('parsed', '已解析'), ('ai_extracted', 'AI 已擷取'), ('under_review', '審核中'), ('approved', '已核准'), ('published', '已發布'), ('archived', '已封存'), ('rejected', '已退回')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='work_type',
            field=models.CharField(choices=[('undergraduate_project', '大學部專題'), ('master_thesis', '碩士論文'), ('research_project', '研究計畫'), ('journal_article', '期刊論文'), ('conference_paper', '研討會論文'), ('other', '其他')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='researchworktransition',
            name='from_status',
            field=models.CharField(choices=[('draft', '草稿'), ('uploaded', '已上傳'), ('parsed', '已解析'), ('ai_extracted', 'AI 已擷取'), ('under_review', '審核中'), ('approved', '已核准'), ('published', '已發布'), ('archived', '已封存'), ('rejected', '已退回')], max_length=24),
        ),
        migrations.AlterField(
            model_name='researchworktransition',
            name='to_status',
            field=models.CharField(choices=[('draft', '草稿'), ('uploaded', '已上傳'), ('parsed', '已解析'), ('ai_extracted', 'AI 已擷取'), ('under_review', '審核中'), ('approved', '已核准'), ('published', '已發布'), ('archived', '已封存'), ('rejected', '已退回')], max_length=24),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('archived', '封存')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='workadvisor',
            name='role',
            field=models.CharField(choices=[('primary', '指導教授'), ('co_advisor', '共同指導'), ('other', '其他')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='relevance',
            field=models.CharField(choices=[('core', '核心'), ('related', '相關'), ('weak', '弱相關'), ('incidental', '偶然提及')], default='related', max_length=16),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='source_type',
            field=models.CharField(choices=[('manual', '人工'), ('imported', '匯入'), ('ai_approved', 'AI 核准候選')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='status',
            field=models.CharField(choices=[('approved', '已核准'), ('archived', '已封存')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AlterField(
            model_name='workmethod',
            name='source_type',
            field=models.CharField(choices=[('manual', '人工'), ('imported', '匯入'), ('ai_approved', 'AI 核准候選')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='workmethod',
            name='status',
            field=models.CharField(choices=[('approved', '已核准'), ('archived', '已封存')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AlterField(
            model_name='workmethod',
            name='usage',
            field=models.CharField(choices=[('primary', '主要'), ('supporting', '輔助')], default='primary', max_length=16),
        ),
    ]
