# Generated by Django 5.2 on 2026-09-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("research", "0004_alter_award_options_alter_featuredwork_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_student_identity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workauthor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "is_active": True,
                    "roles__is_active": True,
                    "roles__slug": "student",
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_work_author_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
