# Generated by Django 5.2.16 on 2026-09-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_student_user_workauthor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='student', max_length=20),
        ),
    ]
