# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=160)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('office', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_is_public', models.BooleanField(default=False)),
                ('profile_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProfessorAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='professors.professor')),
            ],
            options={
                'ordering': ('alias', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='professors_display_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_name', ''), _negated=True), name='professors_normalized_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='professoralias',
            constraint=models.UniqueConstraint(fields=('professor', 'normalized_alias'), name='professors_alias_per_professor_unique'),
        ),
        migrations.AddConstraint(
            model_name='professoralias',
            constraint=models.CheckConstraint(condition=models.Q(('alias', ''), _negated=True), name='professors_alias_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='professoralias',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_alias', ''), _negated=True), name='professors_normalized_alias_not_empty'),
        ),
    ]
