# Generated by Django 5.2.16 on 2026-07-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('display_name', 'id'), 'permissions': (('hard_delete_professor', 'Can hard delete professors referenced by governed research records'),)},
        ),
    ]
