# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('display_name', 'id'), 'permissions': (('hard_delete_professor', '可直接刪除受治理紀錄保護的教師'),), 'verbose_name': '教師', 'verbose_name_plural': '教師'},
        ),
        migrations.AlterModelOptions(
            name='professoralias',
            options={'ordering': ('alias', 'id'), 'verbose_name': '教師別名', 'verbose_name_plural': '教師別名'},
        ),
        migrations.AlterField(
            model_name='professor',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('inactive', '停用'), ('archived', '封存')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='professor',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='public', max_length=20),
        ),
    ]
