# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField()),
                ('template', models.TextField()),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(default='1', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key', '-version'),
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('extraction', 'Metadata extraction'), ('assistant', 'Research assistant'), ('research_navigation', 'Research navigation'), ('teacher_matching', 'Teacher matching'), ('chart_explanation', 'Chart explanation')], max_length=40)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=160)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('page_context', models.JSONField(blank=True, default=dict)),
                ('evidence_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked by policy'), ('not_implemented', 'Not implemented')], db_index=True, default='pending', max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
                ('retrieval_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_requests', to='rag.retrievallog')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_logs', to='ai.promptversion')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='ai_prompt_key_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='ai_prompt_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.CheckConstraint(condition=models.Q(('template', ''), _negated=True), name='ai_prompt_template_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version', ''), _negated=True), name='ai_prompt_schema_version_not_empty'),
        ),
    ]
