# Generated by Django 5.2.16 on 2026-07-18 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('django_session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('page_context', models.JSONField(blank=True, default=dict)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.assistantsession')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='ai_assistan_user_id_2d9447_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantsession',
            index=models.Index(fields=['django_session_key', 'status', '-updated_at'], name='ai_assistan_django__aa2e21_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantsession',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('django_session_key', ''), _negated=True), _connector='OR'), name='ai_assistant_session_has_owner_or_browser_session'),
        ),
        migrations.AddConstraint(
            model_name='assistantsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='ai_assistant_session_status_ended_at_consistent'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_assistan_session_c7d46c_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='ai_assistant_message_content_not_empty'),
        ),
    ]
