# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_assistantsession_assistantmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airequestlog',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'AI 請求紀錄', 'verbose_name_plural': 'AI 請求紀錄'},
        ),
        migrations.AlterModelOptions(
            name='assistantmessage',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'AI 助理訊息', 'verbose_name_plural': 'AI 助理訊息'},
        ),
        migrations.AlterModelOptions(
            name='assistantsession',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'AI 助理對話', 'verbose_name_plural': 'AI 助理對話'},
        ),
        migrations.AlterModelOptions(
            name='promptversion',
            options={'ordering': ('key', '-version'), 'verbose_name': 'Prompt 版本', 'verbose_name_plural': 'Prompt 版本'},
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='purpose',
            field=models.CharField(choices=[('extraction', 'Metadata 擷取'), ('assistant', '研究助理'), ('research_navigation', '研究導航'), ('teacher_matching', '教師推薦'), ('chart_explanation', '圖表解釋')], max_length=40),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('succeeded', '成功'), ('failed', '失敗'), ('blocked', '政策阻擋'), ('not_implemented', '尚未實作')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='assistantmessage',
            name='role',
            field=models.CharField(choices=[('user', '使用者'), ('assistant', '助理')], max_length=16),
        ),
        migrations.AlterField(
            model_name='assistantsession',
            name='status',
            field=models.CharField(choices=[('active', '進行中'), ('ended', '已結束')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='promptversion',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '啟用'), ('retired', '停用')], db_index=True, default='draft', max_length=20),
        ),
    ]
