# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.db.models.deletion
import documents.models
import documents.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, storage=documents.storage.PrivateDocumentStorage(), upload_to=documents.models.private_document_upload_to)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('checksum', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='admin', max_length=20)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='research.researchwork')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_source_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('char_start', models.PositiveBigIntegerField(blank=True, null=True)),
                ('char_end', models.PositiveBigIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('chunk_strategy_version', models.CharField(default='unversioned', max_length=50)),
                ('visibility_scope', models.CharField(blank=True, choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='', help_text="Defaults to the source document's scope and may only be stricter.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ('source_document_id', 'chunk_index'),
            },
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__isnull', True), ('file_size__gt', 0), _connector='OR'), name='documents_source_file_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum', ''), _negated=True), fields=('research_work', 'checksum'), name='documents_source_work_checksum_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('source_document', 'chunk_index'), name='documents_chunk_document_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.CheckConstraint(condition=models.Q(('page_start__isnull', True), ('page_start__gte', 1), _connector='OR'), name='documents_chunk_page_start_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.CheckConstraint(condition=models.Q(('page_end__isnull', True), ('page_start__isnull', True), ('page_end__gte', models.F('page_start')), _connector='OR'), name='documents_chunk_page_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__isnull', True), ('char_start__isnull', True), ('char_end__gte', models.F('char_start')), _connector='OR'), name='documents_chunk_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='documents_chunk_text_not_empty'),
        ),
    ]
