# Generated by Django 5.2.16 on 2026-07-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedocument',
            options={'ordering': ('-uploaded_at', 'id'), 'permissions': (('hard_delete_sourcedocument', 'Can hard delete source documents and protected derived records'),)},
        ),
    ]
