# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_sourcedocument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ('source_document_id', 'chunk_index'), 'verbose_name': '文件段落', 'verbose_name_plural': '文件段落'},
        ),
        migrations.AlterModelOptions(
            name='sourcedocument',
            options={'ordering': ('-uploaded_at', 'id'), 'permissions': (('hard_delete_sourcedocument', '可直接刪除研究文件與衍生資料'),), 'verbose_name': '原始研究文件', 'verbose_name_plural': '原始研究文件'},
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='visibility_scope',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='', help_text="Defaults to the source document's scope and may only be stricter.", max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='extraction_status',
            field=models.CharField(choices=[('pending', '等待中'), ('queued', '已排程'), ('processing', '處理中'), ('succeeded', '成功'), ('failed', '失敗')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='admin', max_length=20),
        ),
    ]
