# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='public', max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.aitag')),
            ],
            options={
                'verbose_name': 'AI tag',
                'verbose_name_plural': 'AI tags',
                'ordering': ('display_name', 'id'),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='taxonomy_aitag_slug_not_empty'), models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='taxonomy_aitag_name_not_empty'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='taxonomy_aitag_parent_not_self')],
            },
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='public', max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.researchfield')),
            ],
            options={
                'verbose_name': 'research field',
                'verbose_name_plural': 'research fields',
                'ordering': ('display_name', 'id'),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='taxonomy_researchfield_slug_not_empty'), models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='taxonomy_researchfield_name_not_empty'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='taxonomy_researchfield_parent_not_self')],
            },
        ),
        migrations.CreateModel(
            name='ResearchMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators only')], db_index=True, default='public', max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='taxonomy.researchmethod')),
            ],
            options={
                'verbose_name': 'research method',
                'verbose_name_plural': 'research methods',
                'ordering': ('display_name', 'id'),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='taxonomy_researchmethod_slug_not_empty'), models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='taxonomy_researchmethod_name_not_empty'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='taxonomy_researchmethod_parent_not_self')],
            },
        ),
    ]
