# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitag',
            options={'ordering': ('display_name', 'id'), 'verbose_name': 'AI 標籤', 'verbose_name_plural': 'AI 標籤'},
        ),
        migrations.AlterModelOptions(
            name='researchfield',
            options={'ordering': ('display_name', 'id'), 'verbose_name': '研究領域', 'verbose_name_plural': '研究領域'},
        ),
        migrations.AlterModelOptions(
            name='researchmethod',
            options={'ordering': ('display_name', 'id'), 'verbose_name': '研究方法', 'verbose_name_plural': '研究方法'},
        ),
        migrations.AlterField(
            model_name='aitag',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('archived', '封存')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='aitag',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchfield',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('archived', '封存')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchfield',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchmethod',
            name='status',
            field=models.CharField(choices=[('active', '啟用'), ('archived', '封存')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchmethod',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='public', max_length=20),
        ),
    ]
