# Generated by Django 5.2.16 on 2026-07-16 08:16

import django.core.validators
import django.db.models.deletion
import rag.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('query_text', models.TextField()),
                ('retrieval_kind', models.CharField(choices=[('keyword', 'Permission-aware keyword evidence'), ('semantic', 'Semantic vector retrieval')], max_length=20)),
                ('permitted_document_scopes', models.JSONField(default=list)),
                ('permitted_research_scopes', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('denied', 'Denied'), ('failed', 'Failed'), ('not_implemented', 'Not implemented')], db_index=True, default='started', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CitationSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('excerpt', models.TextField()),
                ('visibility_scope', models.CharField(choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], help_text='Snapshot of the evidence scope when it was retrieved.', max_length=20)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_citations', to='documents.documentchunk')),
                ('retrieval_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='rag.retrievallog')),
            ],
            options={
                'ordering': ('retrieval_log_id', 'rank', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('stale', 'Stale'), ('failed', 'Failed'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('visibility_scope', models.CharField(blank=True, choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='', max_length=20)),
                ('content_checksum', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_chunk', to='documents.documentchunk')),
            ],
            options={
                'ordering': ('vector_document_id', 'source_chunk__chunk_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=160)),
                ('dimensions', models.PositiveIntegerField()),
                ('embedding', rag.fields.PortableVectorField(help_text='Native pgvector on PostgreSQL; JSON-compatible text on SQLite.')),
                ('input_checksum', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vector_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='rag.vectorchunk')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('stale', 'Stale'), ('failed', 'Failed'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('visibility_scope', models.CharField(blank=True, choices=[('public', 'Public'), ('student', 'Students and staff'), ('teacher', 'Teachers and administrators'), ('admin', 'Administrators')], db_index=True, default='', help_text='Inherited from the source document; it may only be stricter.', max_length=20)),
                ('chunk_strategy_version', models.CharField(default='unversioned', max_length=50)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_document', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='vectorchunk',
            name='vector_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_chunks', to='rag.vectordocument'),
        ),
        migrations.AddConstraint(
            model_name='retrievallog',
            constraint=models.CheckConstraint(condition=models.Q(('query_text', ''), _negated=True), name='rag_retrieval_query_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(fields=('retrieval_log', 'rank'), name='rag_citation_rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.UniqueConstraint(fields=('retrieval_log', 'document_chunk'), name='rag_citation_chunk_unique'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gt', 0)), name='rag_citation_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('excerpt', ''), _negated=True), name='rag_citation_excerpt_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='embeddingrecord',
            constraint=models.UniqueConstraint(fields=('vector_chunk', 'provider', 'model_name', 'input_checksum'), name='rag_embedding_input_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='embeddingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('dimensions__gt', 0)), name='rag_embedding_dimensions_positive'),
        ),
        migrations.AddConstraint(
            model_name='embeddingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('input_checksum', ''), _negated=True), name='rag_embedding_checksum_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='vectorchunk',
            constraint=models.CheckConstraint(condition=models.Q(('content_checksum', ''), _negated=True), name='rag_vector_chunk_checksum_not_empty'),
        ),
    ]
