# Generated by Django 5.2.16 on 2026-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citationsource',
            options={'ordering': ('retrieval_log_id', 'rank', 'id'), 'verbose_name': '引用來源', 'verbose_name_plural': '引用來源'},
        ),
        migrations.AlterModelOptions(
            name='embeddingrecord',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'Embedding 紀錄', 'verbose_name_plural': 'Embedding 紀錄'},
        ),
        migrations.AlterModelOptions(
            name='retrievallog',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': '檢索紀錄', 'verbose_name_plural': '檢索紀錄'},
        ),
        migrations.AlterModelOptions(
            name='vectorchunk',
            options={'ordering': ('vector_document_id', 'source_chunk__chunk_index', 'id'), 'verbose_name': '向量段落', 'verbose_name_plural': '向量段落'},
        ),
        migrations.AlterModelOptions(
            name='vectordocument',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': '向量文件', 'verbose_name_plural': '向量文件'},
        ),
        migrations.AlterField(
            model_name='citationsource',
            name='visibility_scope',
            field=models.CharField(choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], help_text='Snapshot of the evidence scope when it was retrieved.', max_length=20),
        ),
        migrations.AlterField(
            model_name='retrievallog',
            name='retrieval_kind',
            field=models.CharField(choices=[('keyword', '權限感知關鍵字證據'), ('semantic', '語意向量檢索')], max_length=20),
        ),
        migrations.AlterField(
            model_name='retrievallog',
            name='status',
            field=models.CharField(choices=[('started', '開始'), ('completed', '完成'), ('denied', '拒絕'), ('failed', '失敗'), ('not_implemented', '尚未實作')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='vectorchunk',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('ready', '就緒'), ('stale', '過期'), ('failed', '失敗'), ('disabled', '停用')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vectorchunk',
            name='visibility_scope',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vectordocument',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('ready', '就緒'), ('stale', '過期'), ('failed', '失敗'), ('disabled', '停用')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vectordocument',
            name='visibility_scope',
            field=models.CharField(blank=True, choices=[('public', '公開'), ('student', '學生與教職員'), ('teacher', '教師與管理員'), ('admin', '管理員')], db_index=True, default='', help_text='Inherited from the source document; it may only be stricter.', max_length=20),
        ),
    ]
